/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtworkUploadRouteImport } from './routes/artwork-upload'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSamplesRouteImport } from './routes/_authenticated/samples'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPricingRequestsRouteImport } from './routes/_authenticated/pricing-requests'
import { Route as AuthenticatedPortalLinksRouteImport } from './routes/_authenticated/portal-links'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedDataQualityRouteImport } from './routes/_authenticated/data-quality'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedArtworkRouteImport } from './routes/_authenticated/artwork'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated/quotations.index'
import { Route as ApiPublicLeadRequestRouteImport } from './routes/api/public/lead-request'
import { Route as AuthenticatedQuotationsIdRouteImport } from './routes/_authenticated/quotations.$id'
import { Route as AuthenticatedArtworkPendingRouteImport } from './routes/_authenticated/artwork.pending'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkUploadRoute = ArtworkUploadRouteImport.update({
  id: '/artwork-upload',
  path: '/artwork-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSamplesRoute = AuthenticatedSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRequestsRoute =
  AuthenticatedPricingRequestsRouteImport.update({
    id: '/pricing-requests',
    path: '/pricing-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalLinksRoute =
  AuthenticatedPortalLinksRouteImport.update({
    id: '/portal-links',
    path: '/portal-links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataQualityRoute =
  AuthenticatedDataQualityRouteImport.update({
    id: '/data-quality',
    path: '/data-quality',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtworkRoute = AuthenticatedArtworkRouteImport.update({
  id: '/artwork',
  path: '/artwork',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicLeadRequestRoute = ApiPublicLeadRequestRouteImport.update({
  id: '/api/public/lead-request',
  path: '/api/public/lead-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuotationsIdRoute =
  AuthenticatedQuotationsIdRouteImport.update({
    id: '/quotations/$id',
    path: '/quotations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtworkPendingRoute =
  AuthenticatedArtworkPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedArtworkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/artwork-upload': typeof ArtworkUploadRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/artwork': typeof AuthenticatedArtworkRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/data-quality': typeof AuthenticatedDataQualityRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/import': typeof AuthenticatedImportRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/portal-links': typeof AuthenticatedPortalLinksRoute
  '/pricing-requests': typeof AuthenticatedPricingRequestsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/samples': typeof AuthenticatedSamplesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/portal/$token': typeof PortalTokenRoute
  '/artwork/pending': typeof AuthenticatedArtworkPendingRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/api/public/lead-request': typeof ApiPublicLeadRequestRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/artwork-upload': typeof ArtworkUploadRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/artwork': typeof AuthenticatedArtworkRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/data-quality': typeof AuthenticatedDataQualityRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/import': typeof AuthenticatedImportRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/portal-links': typeof AuthenticatedPortalLinksRoute
  '/pricing-requests': typeof AuthenticatedPricingRequestsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/samples': typeof AuthenticatedSamplesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/portal/$token': typeof PortalTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/artwork/pending': typeof AuthenticatedArtworkPendingRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/api/public/lead-request': typeof ApiPublicLeadRequestRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/artwork-upload': typeof ArtworkUploadRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/signup': typeof SignupRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/artwork': typeof AuthenticatedArtworkRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/data-quality': typeof AuthenticatedDataQualityRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/portal-links': typeof AuthenticatedPortalLinksRoute
  '/_authenticated/pricing-requests': typeof AuthenticatedPricingRequestsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/samples': typeof AuthenticatedSamplesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/artwork/pending': typeof AuthenticatedArtworkPendingRoute
  '/_authenticated/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/api/public/lead-request': typeof ApiPublicLeadRequestRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artwork-upload'
    | '/auth'
    | '/register'
    | '/request'
    | '/signup'
    | '/approvals'
    | '/artwork'
    | '/assistant'
    | '/automation'
    | '/campaigns'
    | '/clients'
    | '/competitors'
    | '/complaints'
    | '/data-quality'
    | '/deliveries'
    | '/import'
    | '/knowledge'
    | '/leads'
    | '/meetings'
    | '/orders'
    | '/payments'
    | '/pipeline'
    | '/portal-links'
    | '/pricing-requests'
    | '/production'
    | '/reports'
    | '/samples'
    | '/tasks'
    | '/users'
    | '/portal/$token'
    | '/artwork/pending'
    | '/quotations/$id'
    | '/api/public/lead-request'
    | '/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/artwork-upload'
    | '/auth'
    | '/register'
    | '/request'
    | '/signup'
    | '/approvals'
    | '/artwork'
    | '/assistant'
    | '/automation'
    | '/campaigns'
    | '/clients'
    | '/competitors'
    | '/complaints'
    | '/data-quality'
    | '/deliveries'
    | '/import'
    | '/knowledge'
    | '/leads'
    | '/meetings'
    | '/orders'
    | '/payments'
    | '/pipeline'
    | '/portal-links'
    | '/pricing-requests'
    | '/production'
    | '/reports'
    | '/samples'
    | '/tasks'
    | '/users'
    | '/portal/$token'
    | '/'
    | '/artwork/pending'
    | '/quotations/$id'
    | '/api/public/lead-request'
    | '/quotations'
  id:
    | '__root__'
    | '/_authenticated'
    | '/artwork-upload'
    | '/auth'
    | '/register'
    | '/request'
    | '/signup'
    | '/_authenticated/approvals'
    | '/_authenticated/artwork'
    | '/_authenticated/assistant'
    | '/_authenticated/automation'
    | '/_authenticated/campaigns'
    | '/_authenticated/clients'
    | '/_authenticated/competitors'
    | '/_authenticated/complaints'
    | '/_authenticated/data-quality'
    | '/_authenticated/deliveries'
    | '/_authenticated/import'
    | '/_authenticated/knowledge'
    | '/_authenticated/leads'
    | '/_authenticated/meetings'
    | '/_authenticated/orders'
    | '/_authenticated/payments'
    | '/_authenticated/pipeline'
    | '/_authenticated/portal-links'
    | '/_authenticated/pricing-requests'
    | '/_authenticated/production'
    | '/_authenticated/reports'
    | '/_authenticated/samples'
    | '/_authenticated/tasks'
    | '/_authenticated/users'
    | '/portal/$token'
    | '/_authenticated/'
    | '/_authenticated/artwork/pending'
    | '/_authenticated/quotations/$id'
    | '/api/public/lead-request'
    | '/_authenticated/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArtworkUploadRoute: typeof ArtworkUploadRoute
  AuthRoute: typeof AuthRoute
  RegisterRoute: typeof RegisterRoute
  RequestRoute: typeof RequestRoute
  SignupRoute: typeof SignupRoute
  PortalTokenRoute: typeof PortalTokenRoute
  ApiPublicLeadRequestRoute: typeof ApiPublicLeadRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork-upload': {
      id: '/artwork-upload'
      path: '/artwork-upload'
      fullPath: '/artwork-upload'
      preLoaderRoute: typeof ArtworkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples': {
      id: '/_authenticated/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof AuthenticatedSamplesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing-requests': {
      id: '/_authenticated/pricing-requests'
      path: '/pricing-requests'
      fullPath: '/pricing-requests'
      preLoaderRoute: typeof AuthenticatedPricingRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-links': {
      id: '/_authenticated/portal-links'
      path: '/portal-links'
      fullPath: '/portal-links'
      preLoaderRoute: typeof AuthenticatedPortalLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-quality': {
      id: '/_authenticated/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof AuthenticatedDataQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artwork': {
      id: '/_authenticated/artwork'
      path: '/artwork'
      fullPath: '/artwork'
      preLoaderRoute: typeof AuthenticatedArtworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/lead-request': {
      id: '/api/public/lead-request'
      path: '/api/public/lead-request'
      fullPath: '/api/public/lead-request'
      preLoaderRoute: typeof ApiPublicLeadRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quotations/$id': {
      id: '/_authenticated/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AuthenticatedQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artwork/pending': {
      id: '/_authenticated/artwork/pending'
      path: '/pending'
      fullPath: '/artwork/pending'
      preLoaderRoute: typeof AuthenticatedArtworkPendingRouteImport
      parentRoute: typeof AuthenticatedArtworkRoute
    }
  }
}

interface AuthenticatedArtworkRouteChildren {
  AuthenticatedArtworkPendingRoute: typeof AuthenticatedArtworkPendingRoute
}

const AuthenticatedArtworkRouteChildren: AuthenticatedArtworkRouteChildren = {
  AuthenticatedArtworkPendingRoute: AuthenticatedArtworkPendingRoute,
}

const AuthenticatedArtworkRouteWithChildren =
  AuthenticatedArtworkRoute._addFileChildren(AuthenticatedArtworkRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedArtworkRoute: typeof AuthenticatedArtworkRouteWithChildren
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedDataQualityRoute: typeof AuthenticatedDataQualityRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPortalLinksRoute: typeof AuthenticatedPortalLinksRoute
  AuthenticatedPricingRequestsRoute: typeof AuthenticatedPricingRequestsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSamplesRoute: typeof AuthenticatedSamplesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedQuotationsIdRoute: typeof AuthenticatedQuotationsIdRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedArtworkRoute: AuthenticatedArtworkRouteWithChildren,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedDataQualityRoute: AuthenticatedDataQualityRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPortalLinksRoute: AuthenticatedPortalLinksRoute,
  AuthenticatedPricingRequestsRoute: AuthenticatedPricingRequestsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSamplesRoute: AuthenticatedSamplesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedQuotationsIdRoute: AuthenticatedQuotationsIdRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArtworkUploadRoute: ArtworkUploadRoute,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
  RequestRoute: RequestRoute,
  SignupRoute: SignupRoute,
  PortalTokenRoute: PortalTokenRoute,
  ApiPublicLeadRequestRoute: ApiPublicLeadRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
